// Mocks generated by Mockito 5.5.0 from annotations
// in procedure_remote_data_source_test.dart.
// Do not manually edit this file.
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:dio/dio.dart' as _i2;

class MockDio extends _i1.Mock implements _i2.Dio {}


